FROM python:3.8-alpine

MAINTAINER Dmitrey Kazin

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt

RUN apk update && \
    apk add curl && \
    pip install --upgrade pip && \
    pip install -r requirements.txt

COPY . /app

CMD gunicorn --bind 0.0.0.0:80 app:app --timeout 180
